---

# tasks file for osquery (Debian, Ubuntu specific)

- name: Ensure dirmngr is present for apt-key
  package:
    name: dirmngr
    state: present
  register: pkg_result
  until: pkg_result is success

- name: Setup osquery APT key
  become: yes
  apt_key:
    data: "{{ lookup('file', 'pgp-0x1484120AC4E9F8A1A577AEEE97A80C63C9D8B80B.asc') }}"
    state: present
  tags:
    - osquery
  register: pkg_result
  until: pkg_result is success

- name: Ensure apt-transport-https is installed
  become: yes
  apt:
    name: apt-transport-https
    state: present
  tags:
    - osquery
  register: pkg_result
  until: pkg_result is success

- name: Configure osquery APT repository
  become: yes
  apt_repository:
    repo: "{{ _osquery_repository }}"
    state: present
  tags:
    - osquery
  register: pkg_result
  until: pkg_result is success

- include: apparmor.yml
  when: >
    not (ansible_virtualization_type is defined and
          (ansible_virtualization_type == "lxc" or ansible_virtualization_type == "docker")
        )
