---

- name: get source repository for profiling tools
  git:
    repo: https://github.com/facebook/osquery.git
    dest: /root/osquery
    version: "{{ osquery_git_version | default('081d5053eef2afd94eac3f4b918e83ca7b5061cd') }}"

- name: ensure profiling dependencies are present - pkg
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - python-pip
  register: pkg_result
  until: pkg_result is success
- name: ensure profiling dependencies are present - pip
  pip:
    name: psutil
    state: present
  register: pkg_result
  until: pkg_result is success
- name: profiling
  command: >
    ./tools/analysis/profile.py --config {{ osquery_profiling_conf }} --shell /usr/bin/osqueryi --count 1 --rounds 4
  args:
    chdir: /root/osquery
  changed_when: false
  register: perf
- debug: var=perf.stdout_lines
