---

- name: Ensure selinux package are present
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - selinux-policy
    - selinux-policy-devel
    - setools-console
    - libselinux-python
    - policycoreutils-python

- name: Ensure osquery directory exists
  file:
    dest: /etc/osquery
    state: directory
    mode: '0755'

- name: Ensure osquery selinux policy is set
  template:
    src: "{{ item }}.j2"
    dest: "/etc/osquery/{{ item }}"
    mode: '0600'
    owner: root
  with_items:
    - osquery.fc
    - osquery.sh
    - osquery.te
    - myosquery.te
  register: te

# FIXME!
- name: Generate osquery policy file
  command: "{{ item }}"
  args:
    chdir: /etc/osquery
  with_items:
    - sh -x ./osquery.sh
    - make -f /usr/share/selinux/devel/Makefile myosquery.pp
    - semodule -i myosquery.pp
  when: te is changed

# `sepolicy generate -n osquery --init /usr/bin/osqueryd`     = OK/base
# Refine policy with `audit2allow -i /var/log/audit/audit.log -M osquery`
# `semodule -i osquery.pp`
# FIXME! 'Failed to resolve typeattributeset statement at /etc/selinux/targeted/tmp/modules/400/osquery/cil:2'
# `/usr/libexec/selinux/hll/pp osquery.pp`
# OK as additional policy file
