---

- name: Ensure override folder exists
  file:
    dest: /etc/systemd/system/osqueryd.service.d
    state: directory
    mode: '0755'

# if issue, check /var/log/audit/audit.log
- name: Review osquery systemd options - RestartSec, Seccomp...
  template:
    src: systemd-override.conf.j2
    dest: /etc/systemd/system/osqueryd.service.d/override.conf
    mode: '0644'
    backup: "{{ osquery_backup | default(false) }}"
  notify:
    - reload systemd
    - restart osquery
